// スマートグループ化とPBS構造自動生成

// 型定義を一元化されたファイルからimport
import type { TreeNode } from '@/types'

interface ComponentInstance {
  id: string
  title: string
  basePartId?: string
  instanceName?: string
  modelNumber?: string
  voltage?: string
  communication?: string
  description?: string
  purchaseSiteLink?: string
}

/**
 * コンポーネントをベース部品でグループ化してPBS構造を生成
 */
export function generateSmartPBSStructure(components: ComponentInstance[]): TreeNode[] {
  if (components.length === 0) return []
  
  // ベース部品でグループ化
  const groupedComponents = groupComponentsByBasePartId(components)
  
  const pbsNodes: TreeNode[] = []
  
  groupedComponents.forEach((instances, basePartId) => {
    // 統一処理：単一でも複数でもグループフォルダを作成
    // ただし、単一の場合は直接表示も可能
    const baseName = extractBaseName(instances[0].title)
    const groupName = generatePluralName(baseName)
    
    const children: TreeNode[] = instances.map(instance => ({
      id: instance.id,
      name: instance.instanceName || instance.title,
      type: "component" as const,
      icon: "Wrench",
      basePartId: basePartId
    }))
    
    if (instances.length === 1) {
      // 単一インスタンス：インスタンス名がパターンマッチする場合のみ大本名使用
      const isInstancePattern = /\s+[A-Z]$|\s+\d+$/.test(instances[0].title)
      const displayName = isInstancePattern ? baseName : instances[0].title
      
      pbsNodes.push({
        id: instances[0].id,
        name: displayName, // 条件付きで大本名またはインスタンス名を使用
        type: "component",
        icon: "Wrench",
        basePartId: basePartId
      })
    } else {
      // 複数インスタンス：グループフォルダを作成
      pbsNodes.push({
        id: `group-${basePartId}`,
        name: `${groupName} (${instances.length} items)`,
        type: "folder",
        icon: "Folder",
        children: children,
        basePartId: basePartId,
        instanceCount: instances.length,
        isExpanded: true
      })
    }
  })
  
  return pbsNodes.sort((a, b) => {
    // フォルダを先に、コンポーネントを後に
    if (a.type !== b.type) {
      return a.type === 'folder' ? -1 : 1
    }
    return a.name.localeCompare(b.name)
  })
}

/**
 * ベース部品IDでコンポーネントをグループ化
 */
function groupComponentsByBasePartId(components: ComponentInstance[]): Map<string, ComponentInstance[]> {
  const groups = new Map<string, ComponentInstance[]>()
  
  components.forEach(component => {
    // basePartId がない場合は、部品名ベースで生成
    const groupKey = component.basePartId || `auto-${component.data?.title.toLowerCase().replace(/\s+/g, '-')}`
    
    if (!groups.has(groupKey)) {
      groups.set(groupKey, [])
    }
    groups.get(groupKey)!.push(component)
  })
  
  return groups
}

/**
 * インスタンス名からベース名を抽出
 * 例: "Motor A" → "Motor", "Sensor 3" → "Sensor"
 */
function extractBaseName(instanceName: string): string {
  // 末尾の " A", " B", " 1", " 2" などを除去
  const match = instanceName.match(/^(.+?)\s+([A-Z]|\d+)$/)
  return match ? match[1] : instanceName
}

/**
 * 部品名の複数形を生成
 */
function generatePluralName(baseName: string): string {
  if (baseName.endsWith('y')) {
    return baseName.slice(0, -1) + 'ies' // Battery → Batteries
  } else if (baseName.endsWith('s') || baseName.endsWith('x') || baseName.endsWith('ch') || baseName.endsWith('sh')) {
    return baseName + 'es' // Sensor → Sensors, Switch → Switches
  } else {
    return baseName + 's' // Motor → Motors
  }
}

/**
 * 既存のPBS構造を新しい構造にマイグレーション
 */
export function migratePBSToSmartStructure(
  existingPBS: TreeNode[],
  components: ComponentInstance[]
): TreeNode[] {
  // 既存の手動で作成されたフォルダを保持
  const manualFolders = existingPBS.filter(node => 
    node.type === 'folder' && !node.basePartId
  )
  
  // コンポーネントから自動生成された構造
  const autoGeneratedStructure = generateSmartPBSStructure(components)
  
  // 手動フォルダと自動生成構造を結合
  return [...manualFolders, ...autoGeneratedStructure]
}

/**
 * PBS構造にスマートグループ化を適用する関数
 */
export function applySmartGroupingToPBS(pbsTree: TreeNode[], _componentInstances: any[]): TreeNode[] {
  console.log('🔧 Applying smart grouping to PBS structure...')
  
  // 既存のグループ構造をチェック（重複防止）
  const hasExistingGroups = pbsTree.some(node => 
    node.type === 'folder' && 
    node.basePartId && 
    (node.instanceCount || (node.children && node.children.length > 0))
  )
  
  if (hasExistingGroups) {
    console.log('✅ Existing group structure detected, skipping smart grouping')
    return pbsTree
  }
  
  // 個別インスタンスを検出してグループ化
  const processedTree = [...pbsTree]
  
  // カテゴリ外に表示される個別インスタンスを探す
  const rootComponents = processedTree.filter(node => node.type === 'component')
  const individualInstances = rootComponents.filter(node => 
    /\s+[A-Z]$|\s+\d+$/.test(node.name)
  )
  
  console.log('Found individual instances at root:', individualInstances.map(i => i.name))
  
  if (individualInstances.length === 0) {
    console.log('No individual instances found at root level')
    return processedTree
  }
  
  // ベース部品でグループ化
  const groupedInstances = new Map<string, TreeNode[]>()
  
  individualInstances.forEach(instance => {
    const baseName = instance.name.replace(/\s+[A-Z]$|\s+\d+$/, '')
    if (!groupedInstances.has(baseName)) {
      groupedInstances.set(baseName, [])
    }
    groupedInstances.get(baseName)!.push(instance)
  })
  
  console.log('Grouped instances by base name:', Array.from(groupedInstances.keys()))
  
  // 個別インスタンスをルートから削除
  const filteredTree = processedTree.filter(node => 
    !(node.type === 'component' && /\s+[A-Z]$|\s+\d+$/.test(node.name))
  )
  
  // 各グループに対して適切なカテゴリを見つけて追加
  groupedInstances.forEach((instances, baseName) => {
    if (instances.length > 1) {
      // 複数インスタンスの場合、適切なカテゴリを探す
      const targetCategory = findTargetCategory(filteredTree, baseName)
      
      if (targetCategory) {
        // カテゴリ内にグループフォルダを作成
        const groupFolder: TreeNode = {
          id: `group-${baseName.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
          name: `${baseName}s (${instances.length} items)`,
          type: 'folder',
          icon: 'Folder',
          children: instances.map(instance => ({
            ...instance,
            icon: 'Circle' // 個別インスタンスは○アイコン
          })),
          isExpanded: true
        }
        
        if (!targetCategory.children) {
          targetCategory.children = []
        }
        targetCategory.children.push(groupFolder)
        
        console.log(`✅ Created group folder "${groupFolder.name}" in category "${targetCategory.name}"`)
      } else {
        console.log(`⚠️ No target category found for ${baseName}, adding to root`)
        // 適切なカテゴリが見つからない場合、ルートに追加
        const groupFolder: TreeNode = {
          id: `group-${baseName.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
          name: `${baseName}s (${instances.length} items)`,
          type: 'folder',
          icon: 'Folder',
          children: instances.map(instance => ({
            ...instance,
            icon: 'Circle'
          })),
          isExpanded: true
        }
        filteredTree.push(groupFolder)
      }
    } else {
      // 単一インスタンスの場合、大本名でカテゴリに直接追加
      const targetCategory = findTargetCategory(filteredTree, baseName)
      if (targetCategory) {
        if (!targetCategory.children) {
          targetCategory.children = []
        }
        // 単一の場合は大本名（例：STS3215サーボモータ）で追加
        const baseComponent: TreeNode = {
          id: instances[0].id,
          name: baseName, // インスタンス名ではなく大本名を使用
          type: 'component',
          icon: 'Circle',
          basePartId: instances[0].basePartId
        }
        targetCategory.children.push(baseComponent)
        console.log(`✅ Added single instance "${baseName}" to category "${targetCategory.name}"`)
      } else {
        // 適切なカテゴリが見つからない場合、大本名でルートに追加
        const baseComponent: TreeNode = {
          id: instances[0].id,
          name: baseName,
          type: 'component',
          icon: 'Circle',
          basePartId: instances[0].basePartId
        }
        filteredTree.push(baseComponent)
      }
    }
  })
  
  return filteredTree
}

/**
 * 部品名に基づいて適切なカテゴリを見つける関数
 */
export function findTargetCategory(pbsTree: TreeNode[], baseName: string): TreeNode | null {
  const lowerBaseName = baseName.toLowerCase()
  
  // カテゴリマッピング
  const categoryMappings = {
    'motor': ['actuators', 'drives', 'mechanical'],
    'servo': ['actuators', 'drives', 'mechanical'],
    'sensor': ['sensors', 'vision'],
    'controller': ['control', 'computing'],
    'driver': ['control', 'computing'],
    'power': ['power', 'communication'],
    'cable': ['power', 'communication'],
    'camera': ['vision', 'sensors'],
    'pc': ['computing', 'platform'],
    'board': ['control', 'computing']
  }
  
  // 部品名からカテゴリを推定
  let targetKeywords: string[] = []
  
  for (const [partType, keywords] of Object.entries(categoryMappings)) {
    if (lowerBaseName.includes(partType)) {
      targetKeywords = keywords
      break
    }
  }
  
  if (targetKeywords.length === 0) {
    console.log(`No category mapping found for ${baseName}`)
    return null
  }
  
  // 対応するカテゴリを検索
  for (const category of pbsTree) {
    if (category.type === 'folder') {
      const categoryName = category.name.toLowerCase()
      if (targetKeywords.some(keyword => categoryName.includes(keyword))) {
        console.log(`Found target category "${category.name}" for ${baseName}`)
        return category
      }
    }
  }
  
  console.log(`No matching category found for ${baseName}`)
  return null
}

/**
 * PBS構造からグループ統計を取得
 */
export function getPBSGroupStats(pbsNodes: TreeNode[]): {
  totalComponents: number
  totalGroups: number
  largestGroup: { name: string; count: number } | null
  componentTypes: string[]
} {
  let totalComponents = 0
  let totalGroups = 0
  let largestGroup: { name: string; count: number } | null = null
  const componentTypes = new Set<string>()
  
  function countNodes(nodes: TreeNode[]) {
    nodes.forEach(node => {
      if (node.type === 'folder') {
        totalGroups++
        const count = node.instanceCount || (node.children?.length || 0)
        
        if (!largestGroup || count > largestGroup.count) {
          largestGroup = { name: node.name, count }
        }
        
        if (node.children) {
          countNodes(node.children)
        }
      } else {
        totalComponents++
        const baseName = extractBaseName(node.name)
        componentTypes.add(baseName)
      }
    })
  }
  
  countNodes(pbsNodes)
  
  return {
    totalComponents,
    totalGroups,
    largestGroup,
    componentTypes: Array.from(componentTypes)
  }
}

/**
 * 同じベース部品の全インスタンスを取得
 */
export function getAllInstancesOfBasePart(
  pbsNodes: TreeNode[],
  basePartId: string
): TreeNode[] {
  const instances: TreeNode[] = []
  
  function searchNodes(nodes: TreeNode[]) {
    nodes.forEach(node => {
      if (node.basePartId === basePartId && node.type === 'component') {
        instances.push(node)
      }
      if (node.children) {
        searchNodes(node.children)
      }
    })
  }
  
  searchNodes(pbsNodes)
  return instances
}

/**
 * PBS構造の表示用フォーマット
 */
export function formatPBSForDisplay(pbsNodes: TreeNode[], indent = 0): string[] {
  const lines: string[] = []
  
  pbsNodes.forEach(node => {
    const prefix = '  '.repeat(indent)
    const icon = node.type === 'folder' ? '📁' : '🔧'
    
    lines.push(`${prefix}${icon} ${node.name}`)
    
    if (node.children && node.isExpanded !== false) {
      lines.push(...formatPBSForDisplay(node.children, indent + 1))
    }
  })
  
  return lines
}