// Software prompt generator for external LLM services
import { SystemSuggestion, ComponentSuggestion } from '@/lib/managers/SystemSuggestionManager'
import { RequirementsDocument } from '@/types/requirements'
import { Node } from '@xyflow/react'
import { NodeData, Connection } from '@/types'

interface PromptGeneratorParams {
  systemSuggestion: SystemSuggestion
  requirements: RequirementsDocument
  nodes: Node<NodeData>[]
  connections: Connection[]
}

interface CategorizedComponents {
  microcontroller?: ComponentSuggestion
  sensors: ComponentSuggestion[]
  communication: ComponentSuggestion[]
  power: ComponentSuggestion[]
  display: ComponentSuggestion[]
  actuators: ComponentSuggestion[]
  others: ComponentSuggestion[]
}

interface ConnectionInfo {
  component: string
  pin: string
  type: string
  notes: string
}

export class SoftwarePromptGenerator {
  /**
   * Generate a comprehensive prompt for external LLM services
   */
  generatePrompt(params: PromptGeneratorParams): string {
    const sections = [
      this.generateHeader(),
      this.generateSystemOverview(params.systemSuggestion, params.requirements),
      this.generateHardwareSpecifications(params.systemSuggestion.components),
      this.generateConnectionDetails(params.nodes, params.connections),
      this.generateRequirementsSection(params.requirements),
      this.generateDevelopmentEnvironment(params.systemSuggestion.components),
      this.generateCodeGenerationInstructions(),
      this.generateExampleCodeStructure(params.systemSuggestion),
      this.generateAdditionalConsiderations(params.systemSuggestion)
    ]
    
    return sections.filter(Boolean).join('\n\n---\n\n')
  }

  private generateHeader(): string {
    return `# Embedded System Software Development Request

**Generated by**: ORBOH Hardware System Designer
**Date**: ${new Date().toLocaleString()}
**Purpose**: Generate complete embedded software for the designed hardware system

Please read through all specifications carefully and generate production-ready code.`
  }

  private generateSystemOverview(
    suggestion: SystemSuggestion, 
    requirements: RequirementsDocument
  ): string {
    const purpose = this.extractPrimaryPurpose(requirements)
    
    return `## System Overview

**System Name**: ${suggestion.name}
**Description**: ${suggestion.description}
**Technical Complexity**: ${suggestion.technicalComplexity.toUpperCase()}
**Estimated Development Time**: ${suggestion.estimatedDevelopmentTime.min}-${suggestion.estimatedDevelopmentTime.max} ${suggestion.estimatedDevelopmentTime.unit}

**Primary Purpose**: ${purpose}

**Key Features**:
${suggestion.advantages.map(adv => `- ${adv}`).join('\n')}

**Target Use Cases**:
${suggestion.recommendedFor.map(use => `- ${use}`).join('\n')}`
  }

  private generateHardwareSpecifications(components: ComponentSuggestion[]): string {
    const categorized = this.categorizeComponents(components)
    
    let specs = `## Hardware Components\n\n`
    
    // Microcontroller
    if (categorized.microcontroller) {
      specs += `### Microcontroller\n${this.formatMicrocontroller(categorized.microcontroller)}\n\n`
    }
    
    // Sensors
    if (categorized.sensors.length > 0) {
      specs += `### Sensors\n${this.formatSensors(categorized.sensors)}\n\n`
    }
    
    // Communication
    if (categorized.communication.length > 0) {
      specs += `### Communication Modules\n${this.formatCommunication(categorized.communication)}\n\n`
    }
    
    // Power
    if (categorized.power.length > 0) {
      specs += `### Power Management\n${this.formatPowerComponents(categorized.power)}\n\n`
    }
    
    // Display
    if (categorized.display.length > 0) {
      specs += `### Display/Output\n${this.formatDisplayComponents(categorized.display)}\n\n`
    }
    
    // Others
    if (categorized.others.length > 0) {
      specs += `### Other Components\n${this.formatOtherComponents(categorized.others)}`
    }
    
    return specs.trim()
  }

  private generateConnectionDetails(
    nodes: Node<NodeData>[], 
    connections: Connection[]
  ): string {
    const connectionMatrix = this.buildConnectionMatrix(nodes, connections)
    
    return `## Pin Connections and Interfaces

### Connection Matrix
${this.formatConnectionTable(connectionMatrix)}

### Communication Protocols
${this.identifyProtocols(connections, nodes)}

### Important Notes
- All connections assume 3.3V logic unless otherwise specified
- Pull-up resistors may be required for I2C communication
- Check voltage levels for sensor compatibility
- Ensure proper grounding between components`
  }

  private generateRequirementsSection(requirements: RequirementsDocument): string {
    const reqText = requirements.contentText || ''
    const sections = this.parseRequirementsSections(reqText)
    
    return `## Functional Requirements

### Core Functionality
${sections.functional || '- See original requirements document'}

### Performance Requirements
${sections.performance || '- Real-time response where applicable\n- Efficient power management\n- Reliable operation'}

### User Interface Requirements
${sections.interface || '- Status indicators\n- User input handling\n- Feedback mechanisms'}

### Safety and Reliability
${sections.safety || '- Fail-safe mechanisms\n- Error recovery\n- Data validation'}`
  }

  private generateDevelopmentEnvironment(components: ComponentSuggestion[]): string {
    const mcu = components.find(c => c.type === 'microcontroller')
    const platform = this.determinePlatform(mcu)
    
    return `## Development Environment

### Recommended IDE and Framework
${platform.ide}

### Required Libraries
${platform.libraries}

### Development Board Setup
${platform.setup}

### Debugging Tools
${platform.debugging}`
  }

  private generateCodeGenerationInstructions(): string {
    return `## Code Generation Requirements

Please generate the following components:

### 1. Main Program Structure
- **Setup Function**
  - Initialize all hardware peripherals
  - Configure communication interfaces
  - Set up interrupt handlers
  - Initialize global variables

- **Main Loop**
  - Non-blocking state machine implementation
  - Sensor reading with appropriate intervals
  - Data processing and decision making
  - Communication handling
  - Error checking and recovery

### 2. Hardware Abstraction Layer (HAL)
- **Pin Definitions** (config.h)
  - All GPIO assignments
  - Communication pins (I2C, SPI, UART)
  - Analog input configurations
  - PWM outputs

- **Hardware Initialization**
  - Peripheral setup functions
  - Clock configuration
  - Power management settings

### 3. Component Drivers
- **Sensor Drivers**
  - Initialization routines
  - Data reading functions
  - Calibration methods
  - Error handling

- **Communication Drivers**
  - Protocol implementation
  - Message formatting
  - Error detection/correction

### 4. Application Logic
- **Core Business Logic**
  - Main application state machine
  - Decision algorithms
  - Data processing functions

- **User Interaction**
  - Input handling
  - Output/display updates
  - Feedback mechanisms

### 5. Safety and Diagnostics
- **Watchdog Timer**
  - Implementation and feeding strategy
  - Recovery mechanisms

- **Error Handling**
  - Comprehensive error codes
  - Recovery procedures
  - Logging capabilities

- **Self-Test Routines**
  - Power-on self-test
  - Periodic health checks
  - Diagnostic reporting`
  }

  private generateExampleCodeStructure(suggestion: SystemSuggestion): string {
    const mcu = suggestion.components.find(c => c.type === 'microcontroller')
    const framework = this.determineFramework(mcu)
    
    return `## Suggested Project Structure

\`\`\`
${suggestion.name.toLowerCase().replace(/\s+/g, '_')}/
├── src/
│   ├── main.${framework.extension}
│   ├── config.h
│   ├── hal/
│   │   ├── gpio.${framework.extension}
│   │   ├── i2c.${framework.extension}
│   │   ├── spi.${framework.extension}
│   │   └── uart.${framework.extension}
│   ├── drivers/
│   │   ├── sensors/
│   │   │   └── [sensor_drivers]
│   │   ├── communication/
│   │   │   └── [comm_drivers]
│   │   └── display/
│   │       └── [display_drivers]
│   ├── app/
│   │   ├── state_machine.${framework.extension}
│   │   ├── data_processor.${framework.extension}
│   │   └── user_interface.${framework.extension}
│   └── utils/
│       ├── error_handler.${framework.extension}
│       ├── debug.${framework.extension}
│       └── helpers.${framework.extension}
├── lib/
│   └── [external_libraries]
├── test/
│   └── [unit_tests]
├── ${framework.configFile}
├── README.md
└── docs/
    ├── hardware_setup.md
    └── api_reference.md
\`\`\`

### Key Implementation Notes:
- Use header guards in all .h files
- Implement proper namespacing or prefixing
- Follow MISRA-C guidelines where applicable
- Document all public functions
- Include unit tests for critical functions`
  }

  private generateAdditionalConsiderations(suggestion: SystemSuggestion): string {
    return `## Additional Considerations

### Power Management
- Implement sleep modes where appropriate
- Consider battery life optimization
- Use interrupt-driven design for power efficiency

### Memory Management
- Avoid dynamic memory allocation
- Use fixed-size buffers
- Monitor stack usage
- Implement circular buffers for data logging

### Timing Considerations
- Use hardware timers for precise timing
- Implement timeouts for all blocking operations
- Consider RTOS for complex timing requirements

### Future Expansion
- Design modular architecture
- Use configuration files for easy updates
- Implement versioning system
- Plan for OTA updates if applicable

### Testing Strategy
- Unit tests for individual functions
- Integration tests for component interaction
- System tests for end-to-end functionality
- Stress tests for reliability

### Documentation Requirements
- Inline code comments
- API documentation
- Hardware connection guide
- Troubleshooting guide
- Example usage scenarios`
  }

  // Helper methods
  private categorizeComponents(components: ComponentSuggestion[]): CategorizedComponents {
    const categorized: CategorizedComponents = {
      sensors: [],
      communication: [],
      power: [],
      display: [],
      actuators: [],
      others: []
    }
    
    components.forEach(comp => {
      switch (comp.type) {
        case 'microcontroller':
          categorized.microcontroller = comp
          break
        case 'sensor':
          categorized.sensors.push(comp)
          break
        case 'communication':
          categorized.communication.push(comp)
          break
        case 'power':
          categorized.power.push(comp)
          break
        case 'display':
          categorized.display.push(comp)
          break
        case 'actuator':
          categorized.actuators.push(comp)
          break
        default:
          categorized.others.push(comp)
      }
    })
    
    return categorized
  }

  private formatMicrocontroller(mcu: ComponentSuggestion): string {
    const specs = mcu.specifications
    return `- **Model**: ${mcu.modelNumber || mcu.name}
- **Architecture**: ${specs.architecture || 'N/A'}
- **Clock Speed**: ${specs.clockSpeed || 'N/A'}
- **Memory**: ${specs.memory || 'N/A'}
- **GPIO Pins**: ${specs.gpioPins || 'N/A'}
- **Key Features**: ${specs.features || mcu.reasoning}
- **Development Cost**: ${mcu.cost.currency}${mcu.cost.estimated}`
  }

  private formatSensors(sensors: ComponentSuggestion[]): string {
    return sensors.map((sensor, idx) => {
      const specs = sensor.specifications
      return `${idx + 1}. **${sensor.name}${sensor.modelNumber ? ` (${sensor.modelNumber})` : ''}**
   - Interface: ${specs.interface || 'N/A'}
   - Range: ${specs.range || 'N/A'}
   - Accuracy: ${specs.accuracy || 'N/A'}
   - Power: ${specs.power || 'N/A'}
   - Purpose: ${sensor.reasoning}`
    }).join('\n\n')
  }

  private formatCommunication(comm: ComponentSuggestion[]): string {
    return comm.map((module, idx) => {
      const specs = module.specifications
      return `${idx + 1}. **${module.name}${module.modelNumber ? ` (${module.modelNumber})` : ''}**
   - Protocol: ${specs.protocol || 'N/A'}
   - Range: ${specs.range || 'N/A'}
   - Data Rate: ${specs.dataRate || 'N/A'}
   - Power: ${specs.power || 'N/A'}
   - Purpose: ${module.reasoning}`
    }).join('\n\n')
  }

  private formatPowerComponents(power: ComponentSuggestion[]): string {
    return power.map((comp, idx) => {
      const specs = comp.specifications
      return `${idx + 1}. **${comp.name}**
   - Type: ${specs.type || 'N/A'}
   - Input: ${specs.input || 'N/A'}
   - Output: ${specs.output || 'N/A'}
   - Efficiency: ${specs.efficiency || 'N/A'}`
    }).join('\n\n')
  }

  private formatDisplayComponents(display: ComponentSuggestion[]): string {
    return display.map((comp, idx) => {
      const specs = comp.specifications
      return `${idx + 1}. **${comp.name}**
   - Type: ${specs.type || 'N/A'}
   - Resolution: ${specs.resolution || 'N/A'}
   - Interface: ${specs.interface || 'N/A'}
   - Power: ${specs.power || 'N/A'}`
    }).join('\n\n')
  }

  private formatOtherComponents(others: ComponentSuggestion[]): string {
    return others.map((comp, idx) => {
      return `${idx + 1}. **${comp.name}** - ${comp.reasoning}`
    }).join('\n')
  }

  private buildConnectionMatrix(
    nodes: Node<NodeData>[], 
    connections: Connection[]
  ): ConnectionInfo[] {
    const matrix: ConnectionInfo[] = []
    
    // Extract connection information from nodes and connections
    connections.forEach(conn => {
      const sourceNode = nodes.find(n => n.id === conn.source)
      const targetNode = nodes.find(n => n.id === conn.target)
      
      if (sourceNode && targetNode) {
        matrix.push({
          component: sourceNode.data.title,
          pin: conn.sourceHandle || 'N/A',
          type: this.determineConnectionType(conn),
          notes: `Connected to ${targetNode.data.title} (${conn.targetHandle || 'N/A'})`
        })
      }
    })
    
    return matrix
  }

  private formatConnectionTable(connections: ConnectionInfo[]): string {
    if (connections.length === 0) {
      return 'No connections defined. Please specify connections based on component datasheets.'
    }
    
    let table = '| Component | Pin | Type | Notes |\n'
    table += '|-----------|-----|------|-------|\n'
    
    connections.forEach(conn => {
      table += `| ${conn.component} | ${conn.pin} | ${conn.type} | ${conn.notes} |\n`
    })
    
    return table
  }

  private identifyProtocols(connections: Connection[], nodes: Node<NodeData>[]): string {
    const protocols = new Set<string>()
    
    // Analyze connections to identify protocols
    connections.forEach(conn => {
      if (conn.sourceHandle?.includes('I2C') || conn.targetHandle?.includes('I2C')) {
        protocols.add('I2C')
      }
      if (conn.sourceHandle?.includes('SPI') || conn.targetHandle?.includes('SPI')) {
        protocols.add('SPI')
      }
      if (conn.sourceHandle?.includes('UART') || conn.targetHandle?.includes('UART')) {
        protocols.add('UART')
      }
    })
    
    // Also check node descriptions
    nodes.forEach(node => {
      const desc = (node.data.description || '').toLowerCase()
      if (desc.includes('i2c')) protocols.add('I2C')
      if (desc.includes('spi')) protocols.add('SPI')
      if (desc.includes('uart') || desc.includes('serial')) protocols.add('UART')
      if (desc.includes('onewire') || desc.includes('1-wire')) protocols.add('OneWire')
    })
    
    if (protocols.size === 0) {
      return 'Standard GPIO and analog interfaces'
    }
    
    return Array.from(protocols).map(p => `- ${p}`).join('\n')
  }

  private extractPrimaryPurpose(requirements: RequirementsDocument): string {
    const text = requirements.contentText || ''
    const lines = text.split('\n')
    
    // Look for purpose or objective sections
    for (const line of lines) {
      if (line.toLowerCase().includes('purpose') || 
          line.toLowerCase().includes('objective') ||
          line.toLowerCase().includes('goal')) {
        return line.replace(/[#*-]/g, '').trim()
      }
    }
    
    // Return first non-empty line as fallback
    return lines.find(l => l.trim().length > 10)?.trim() || 'System implementation based on requirements'
  }

  private parseRequirementsSections(text: string): Record<string, string> {
    const sections: Record<string, string> = {}
    const lines = text.split('\n')
    let currentSection = ''
    let currentContent: string[] = []
    
    lines.forEach(line => {
      if (line.startsWith('#') && line.includes('requirement')) {
        if (currentSection && currentContent.length > 0) {
          sections[currentSection] = currentContent.join('\n').trim()
        }
        
        if (line.toLowerCase().includes('functional')) {
          currentSection = 'functional'
        } else if (line.toLowerCase().includes('performance')) {
          currentSection = 'performance'
        } else if (line.toLowerCase().includes('interface')) {
          currentSection = 'interface'
        } else if (line.toLowerCase().includes('safety')) {
          currentSection = 'safety'
        }
        currentContent = []
      } else if (currentSection) {
        currentContent.push(line)
      }
    })
    
    // Save last section
    if (currentSection && currentContent.length > 0) {
      sections[currentSection] = currentContent.join('\n').trim()
    }
    
    return sections
  }

  private determinePlatform(mcu?: ComponentSuggestion): {
    ide: string
    libraries: string
    setup: string
    debugging: string
  } {
    if (!mcu) {
      return {
        ide: '- Arduino IDE or PlatformIO\n- Choose based on your preference',
        libraries: '- Standard Arduino libraries\n- Component-specific libraries as needed',
        setup: '- Install appropriate board support package\n- Configure upload settings',
        debugging: '- Serial monitor for debug output\n- Logic analyzer for protocol debugging'
      }
    }
    
    const name = mcu.name.toLowerCase()
    
    if (name.includes('esp32')) {
      return {
        ide: '- **PlatformIO** (recommended) or Arduino IDE\n- ESP-IDF for advanced features',
        libraries: '- WiFi and Bluetooth libraries\n- AsyncWebServer for web interface\n- ArduinoJson for data handling\n- Component-specific libraries',
        setup: '- Install ESP32 board support\n- Select correct board variant\n- Configure partition scheme\n- Set upload speed to 921600',
        debugging: '- Built-in USB serial converter\n- ESP32 Exception Decoder\n- WiFi debug terminal\n- JTAG debugging support'
      }
    } else if (name.includes('arduino')) {
      return {
        ide: '- **Arduino IDE** 2.0 or later\n- PlatformIO for professional development',
        libraries: '- Wire.h for I2C\n- SPI.h for SPI communication\n- Sensor-specific libraries\n- LiquidCrystal for LCD',
        setup: '- No additional setup required\n- Select correct board type\n- Choose appropriate programmer',
        debugging: '- Serial monitor (9600 baud default)\n- LED indicators for status\n- Oscilloscope for timing issues'
      }
    } else if (name.includes('stm32')) {
      return {
        ide: '- **STM32CubeIDE** (recommended)\n- PlatformIO with STM32 platform\n- Keil or IAR for commercial use',
        libraries: '- STM32 HAL libraries\n- FreeRTOS for complex applications\n- STM32duino for Arduino compatibility',
        setup: '- Install STM32CubeMX for configuration\n- Configure clock tree\n- Set up debug probe (ST-Link)\n- Generate initialization code',
        debugging: '- SWD debugging with ST-Link\n- Real-time variable watch\n- ITM printf for debug output\n- Power consumption analysis'
      }
    }
    
    // Default for unknown MCUs
    return {
      ide: '- PlatformIO (universal support)\n- Manufacturer\'s IDE\n- VS Code with extensions',
      libraries: '- MCU vendor libraries\n- Open-source alternatives\n- Protocol libraries as needed',
      setup: '- Install board support package\n- Configure programmer\n- Set clock and fuse bits\n- Verify toolchain',
      debugging: '- Serial debug output\n- In-circuit debugger\n- Logic analyzer\n- Oscilloscope for timing'
    }
  }

  private determineFramework(mcu?: ComponentSuggestion): {
    extension: string
    configFile: string
  } {
    if (!mcu) {
      return { extension: 'cpp', configFile: 'platformio.ini' }
    }
    
    const name = mcu.name.toLowerCase()
    
    if (name.includes('arduino') || name.includes('esp')) {
      return { extension: 'cpp', configFile: 'platformio.ini' }
    } else if (name.includes('stm32')) {
      return { extension: 'c', configFile: '.ioc' }
    } else if (name.includes('pic')) {
      return { extension: 'c', configFile: 'project.X' }
    }
    
    return { extension: 'c', configFile: 'Makefile' }
  }

  private determineConnectionType(connection: Connection): string {
    const handle = (connection.sourceHandle || connection.targetHandle || '').toLowerCase()
    
    if (handle.includes('i2c')) return 'I2C'
    if (handle.includes('spi')) return 'SPI'
    if (handle.includes('uart')) return 'UART'
    if (handle.includes('analog')) return 'Analog'
    if (handle.includes('pwm')) return 'PWM'
    if (handle.includes('gpio')) return 'Digital I/O'
    
    return 'Digital I/O'
  }
}